module.exports = [
  { name: 'Argentina', id: '37i9dQZEVXbMMy2roB9myp' },
  { name: 'Australia', id: '37i9dQZEVXbJPcfkRz0wJ0' },
  { name: 'Austria', id: '37i9dQZEVXbKNHh6NIXu36' },
  { name: 'Belgium', id: '37i9dQZEVXbJNSeeHswcKB' },
  { name: 'Bolivia', id: '37i9dQZEVXbJqfMFK4d691' },
  { name: 'Brazil', id: '37i9dQZEVXbMXbN3EUUhlg' },
  { name: 'Bulgaria', id: '37i9dQZEVXbNfM2w2mq1B8' },
  { name: 'Canada', id: '37i9dQZEVXbKj23U1GF4IR' },
  { name: 'Chile', id: '37i9dQZEVXbL0GavIqMTeb' },
  { name: 'Colombia', id: '37i9dQZEVXbOa2lmxNORXQ' },
  { name: 'Costa Rica', id: '37i9dQZEVXbMZAjGMynsQX' },
  { name: 'Czech Republic', id: '37i9dQZEVXbIP3c3fqVrJY' },
  { name: 'Denmark', id: '37i9dQZEVXbL3J0k32lWnN' },
  { name: 'Dominican Republic', id: '37i9dQZEVXbKAbrMR8uuf7' },
  { name: 'Ecuador', id: '37i9dQZEVXbJlM6nvL1nD1' },
  { name: 'El Salvador', id: '37i9dQZEVXbLxoIml4MYkT' },
  { name: 'Estonia', id: '37i9dQZEVXbLesry2Qw2xS' },
  { name: 'Finland', id: '37i9dQZEVXbMxcczTSoGwZ' },
  { name: 'France', id: '37i9dQZEVXbIPWwFssbupI' },
  { name: 'Germany', id: '37i9dQZEVXbJiZcmkrIHGU' },
  { name: 'Greece', id: '37i9dQZEVXbJqdarpmTJDL' },
  { name: 'Guatemala', id: '37i9dQZEVXbLy5tBFyQvd4' },
  { name: 'Honduras', id: '37i9dQZEVXbJp9wcIM9Eo5' },
  { name: 'Hongkong', id: '37i9dQZEVXbLwpL8TjsxOG' },
  { name: 'Hungary', id: '37i9dQZEVXbNHwMxAkvmF8' },
  { name: 'Iceland', id: '37i9dQZEVXbKMzVsSGQ49S' },
  { name: 'India', id: '37i9dQZEVXbLZ52XmnySJg' },
  { name: 'Indonesia', id: '37i9dQZEVXbObFQZ3JLcXt' },
  { name: 'Ireland', id: '37i9dQZEVXbKM896FDX8L1' },
  { name: 'Israel', id: '37i9dQZEVXbJ6IpvItkve3' },
  { name: 'Italy', id: '37i9dQZEVXbIQnj7RRhdSX' },
  { name: 'Japan', id: '37i9dQZEVXbKXQ4mDTEBXq' },
  { name: 'Latvia', id: '37i9dQZEVXbJWuzDrTxbKS' },
  { name: 'Lithuania', id: '37i9dQZEVXbMx56Rdq5lwc' },
  { name: 'Luxemburg', id: '37i9dQZEVXbKGcyg6TFGx6' },
  { name: 'Malaysia', id: '37i9dQZEVXbJlfUljuZExa' },
  { name: 'Malta', id: '37i9dQZEVXbMD2H5HJqmx9' },
  { name: 'Mexico', id: '37i9dQZEVXbO3qyFxbkOE1' },
  { name: 'Netherlands', id: '37i9dQZEVXbKCF6dqVpDkS' },
  { name: 'New Zealand', id: '37i9dQZEVXbM8SIrkERIYl' },
  { name: 'Nicaragua', id: '37i9dQZEVXbISk8kxnzfCq' },
  { name: 'Norway', id: '37i9dQZEVXbJvfa0Yxg7E7' },
  { name: 'Panama', id: '37i9dQZEVXbKypXHVwk1f0' },
  { name: 'Paraguay', id: '37i9dQZEVXbNOUPGj7tW6T' },
  { name: 'Peru', id: '37i9dQZEVXbJfdy5b0KP7W' },
  { name: 'Philippines', id: '37i9dQZEVXbNBz9cRCSFkY' },
  { name: 'Poland', id: '37i9dQZEVXbN6itCcaL3Tt' },
  { name: 'Portugal', id: '37i9dQZEVXbKyJS56d1pgi' },
  { name: 'Romania', id: '37i9dQZEVXbNZbJ6TZelCq' },
  { name: 'Singapore', id: '37i9dQZEVXbK4gjvS1FjPY' },
  { name: 'Slovakia', id: '37i9dQZEVXbKIVTPX9a2Sb' },
  { name: 'South Africa', id: '37i9dQZEVXbMH2jvi6jvjk' },
  { name: 'Spain', id: '37i9dQZEVXbNFJfN1Vw8d9' },
  { name: 'Sweden', id: '37i9dQZEVXbLoATJ81JYXz' },
  { name: 'Switzerland', id: '37i9dQZEVXbJiyhoAPEfMK' },
  { name: 'Taiwan', id: '37i9dQZEVXbMnZEatlMSiu' },
  { name: 'Thailand', id: '37i9dQZEVXbMnz8KIWsvf9' },
  { name: 'Turkey', id: '37i9dQZEVXbIVYVBNw9D5K' },
  { name: 'United Kingdom', id: '37i9dQZEVXbLnolsZ8PSNw' },
  { name: 'United States', id: '37i9dQZEVXbLRQDuF5jeBp' },
  { name: 'Uruguay', id: '37i9dQZEVXbMJJi3wgRbAy' },
  { name: 'Vietnam', id: '37i9dQZEVXbLdGSmz6xilI' },
]
